# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Pareidoscope"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

template: "template_toolkit"
engines:
    template_toolkit:
        encoding:  'utf8'
        start_tag: '[%'
        end_tag:   '%]'

# store session information with YAML
session: "YAML"


#----------------------------
# PAREIDOSCOPE CONFIGURATION
#----------------------------

# database connections
plugins:
    Database:
        driver: "SQLite"
        database: "public/cache/cache.sqlite"
        on_connect_do:
            - "PRAGMA foreign_keys = ON"
            - "PRAGMA cache_size = 50000"
            - "PRAGMA encoding = 'UTF-8'"
            - "CREATE TABLE IF NOT EXISTS queries (qid INTEGER PRIMARY KEY, corpus TEXT NOT NULL, class VARCHAR(10) NOT NULL, query TEXT NOT NULL, qlen INTEGER NOT NULL, time INTEGER NOT NULL, r1 INTEGER NOT NULL, n INTEGER NOT NULL, UNIQUE (corpus, class, query))"
            - "CREATE TRIGGER IF NOT EXISTS clean AFTER INSERT ON queries BEGIN SELECT logquery(class, query, datetime(time, 'unixepoch', 'localtime')) FROM queries WHERE qid = new.qid; SELECT rmfile(qid) FROM queries WHERE time < new.time - 1800; DELETE FROM queries WHERE time < new.time - 1800; END;"

# paths
query_log: "public/cache/queries.log"
registry: "corpora/registry"
cache_database: "public/cache/cache.sqlite"
cqp_cache: "public/cache/cqp"

# maximal cache size in MBytes
cache_size: 4096
# maximal storage time before query results expire (in hours)
cache_expire: 12

# corpora
corpora:
    - available: 1
      display_name: "OANC"
      tagset: "penn extended"
      corpus: "OANC"
      tokens: 18065587
      sentences: 897087
      database: "corpora/databases/oanc.sqlite"
      ngram_length: 9
      pos_ngrams: 9145106355
      chunk_ngrams: 113826088
      localdata: "/opt/pareidoscope/oanc"
      machines:
          - ["clue22", 4878, 8487]
          - ["clue23", 4878, 8487]
          - ["clue14", 4878, 8487]
          - ["clue15", 4878, 8487]
    - available: 1
      display_name: "ANC MASC I"
      tagset: "penn extended"
      corpus: "ANC_MASC"
      tokens: 94808
      sentences: 5401
      database: "corpora/databases/anc_masc.sqlite"
      ngram_length: 9
      pos_ngrams: 129759830
      chunk_ngrams: 4120767
      localdata: "/opt/pareidoscope/oanc"
      machines:
          - ["clue22", 4878, 8487]
          - ["clue23", 4878, 8487]
          - ["clue14", 4878, 8487]
          - ["clue15", 4878, 8487]

# tagsets
tagsets:
    penn_extended:
        ADJ: ["CD", "JJ", "JJR", "JJS"]
        ADV: ["RB", "RBR", "RBS", "RP", "WRB"]
        CONJ/PREP: ["CC", "IN", "TO"]
        DET: ["DT", "PDT"]
        INTERJ: ["UH"]
        PRON: ["EX", "PRP", "PRP$", "WDT", "WP", "WP$"]
        PUNC: ["''", "(", ")", "[", "]", "{", "}", ",", ".", ":", "``", "HYPH",  "NFP"]
        SUBST: ["NN", "NNP", "NNPS", "NNS"]
        UNC: ["#", "$", "AFX", "FW", "LS", "POS", "SYM", "XX"]
        VERB: ["MD", "VB", "VBD", "VBG", "VBN", "VBP", "VBZ"]
    c5:
        ADJ: ["AJ0", "AJC", "AJS", "CRD", "DT0", "ORD"]
        ADV: ["AV0", "AVP", "AVQ", "XX0"]
        ART: ["AT0"]
        CONJ: ["CJC", "CJS", "CJT"]
        INTERJ: ["ITJ"]
        PREP: ["PRF", "PRP", "TO0"]
        PRON: ["DPS", "DTQ", "EX0", "PNI", "PNP", "PNQ", "PNX"]
        PUNC: ["PUL", "PUN", "PUQ", "PUR"]
        SUBST: ["NN0", "NN1", "NN2", "NP0", "ZZ0"]
        UNC: ["POS", "UNC"]
        VERB: ["VBB", "VBD", "VBG", "VBI", "VBN", "VBZ", "VDB", "VDD", "VDG", "VDI", "VDN", "VDZ", "VHB", "VHD", "VHG", "VHI", "VHN", "VHZ", "VM0", "VVB", "VVD", "VVG", "VVI", "VVN", "VVZ"]
